export const topSellerData = [
  {
    _id: "645a2693699fe9b1347760bc",
    sellerName: "Istiak Ahmed",
    sellerEmail: "istiakahmed180@gmail.com",
    sellerPhone: "1734604086",
    sellerProfilePicture: "https://i.ibb.co/L99xrbX/Istiak-Ahmed.png",
    name: "Syngenta HPH - 5531 Chilli Seeds",
    images: [
      "https://i.ibb.co/8d101Wz/Image-1.webp",
      "https://i.ibb.co/0B0f87G/Image-2.webp",
      "https://i.ibb.co/QHH9mLC/Image-3.webp",
      "https://i.ibb.co/G7CQMDk/Image-4.webp",
    ],
    oldPrice: 770,
    newPrice: 630,
    size: [],
    stock: "INSTOCK",
    rating: 5,
    description:
      "Chili seeds are the small, dried seeds of the chili pepper plant. They are often used by gardeners and farmers to grow their own chili plants. Chili peppers are popular for their spicy and flavorful fruit, which can be used fresh, dried, or ground into a powder.\n\nChili seeds are typically sold in packets and can be grown in gardens, raised beds, or containers. They require full sun and well-draining soil, and can be started indoors or outdoors, depending on the climate and growing season.\n\nThere are many different varieties of chili seeds available, each with its own unique flavor, heat level, and size. Some popular varieties include jalapeño, habanero, cayenne, and Thai chili peppers.\n\nWhen selecting chili seeds, it's important to consider factors such as the plant's growth habit, disease resistance, and heat level. With proper care and maintenance, chili seeds can yield bountiful harvests of spicy and flavorful peppers.",
    role: "seller",
    additionalInfo: [{}],
    totalSells: 0,
    totalQuantity: 0,
    category: "Seeds",
    brand: "Syngenta",
    date: "05/09/23 04:54 pm",
    __v: 0,
  },
  {
    _id: "645a2a31699fe9b13477611d",
    sellerName: "Istiak Ahmed",
    sellerEmail: "istiakahmed180@gmail.com",
    sellerPhone: "1734604086",
    sellerProfilePicture: "https://i.ibb.co/L99xrbX/Istiak-Ahmed.png",
    name: "Multiplex Yodha Insecticide",
    images: [
      "https://i.ibb.co/TqL8nj1/Image-1.webp",
      "https://i.ibb.co/crNX6gb/Image-2.webp",
      "https://i.ibb.co/ggDxnxF/Image-3.webp",
      "https://i.ibb.co/NLhmCXK/Image-4.webp",
    ],
    oldPrice: 455,
    newPrice: 340,
    size: [],
    stock: "INSTOCK",
    rating: 0,
    description:
      "Multiplex Yodha Insecticide is a broad-spectrum insecticide designed to control a wide range of insect pests that can cause damage to crops, gardens, and other plants. It is commonly used by farmers, gardeners, and landscapers to protect their crops and plants from harmful insects.\n\nThe active ingredient in Multiplex Yodha Insecticide is Imidacloprid, which belongs to a class of chemicals called neonicotinoids. This chemical works by interfering with the nervous system of insects, causing paralysis and ultimately leading to their death.\n\nMultiplex Yodha Insecticide is typically applied as a spray or as a soil drench. It is effective against a variety of insect pests, including aphids, thrips, whiteflies, mealybugs, and leafhoppers.\n\nWhen using Multiplex Yodha Insecticide, it's important to follow the manufacturer's instructions carefully, as overuse or misuse can lead to unintended environmental consequences. It is also important to be aware of the potential risks to non-target organisms, such as bees and other beneficial insects, and to use the product responsibly and in accordance with local regulations.\n\nOverall, Multiplex Yodha Insecticide can be an effective tool for controlling insect pests and protecting crops and plants, but it should be used judiciously and with care to minimize potential risks to the environment and non-target organisms.",
    role: "seller",
    additionalInfo: [{}],
    totalSells: 3,
    totalQuantity: 0,
    category: "Insecticides",
    brand: "Multiplex",
    date: "05/09/23 05:09 pm",
    __v: 0,
  },
  {
    _id: "645a2b48699fe9b13477614c",
    sellerName: "Istiak Ahmed",
    sellerEmail: "istiakahmed180@gmail.com",
    sellerPhone: "1734604086",
    sellerProfilePicture: "https://i.ibb.co/L99xrbX/Istiak-Ahmed.png",
    name: "Bayer Oberon Insecticide",
    images: [
      "https://i.ibb.co/PF76S9L/Image-1.webp",
      "https://i.ibb.co/WGPWjMD/Image-2.webp",
      "https://i.ibb.co/9rtYShv/Image-3.webp",
      "https://i.ibb.co/D8BbyKQ/Image-4.webp",
    ],
    oldPrice: 725,
    newPrice: 590,
    size: [],
    stock: "INSTOCK",
    rating: 0,
    description:
      "Bayer Oberon Insecticide is a broad-spectrum insecticide designed to control a range of insect pests that can cause damage to crops, gardens, and other plants. It is commonly used by farmers, gardeners, and landscapers to protect their crops and plants from harmful insects.\n\nThe active ingredient in Bayer Oberon Insecticide is Spiromesifen, which belongs to a class of chemicals called tetronic acids. This chemical works by disrupting the normal function of the insect's nervous system, causing paralysis and ultimately leading to their death.\n\nBayer Oberon Insecticide is typically applied as a spray or as a soil drench. It is effective against a variety of insect pests, including spider mites, thrips, whiteflies, and aphids.\n\nWhen using Bayer Oberon Insecticide, it's important to follow the manufacturer's instructions carefully, as overuse or misuse can lead to unintended environmental consequences. It is also important to be aware of the potential risks to non-target organisms, such as bees and other beneficial insects, and to use the product responsibly and in accordance with local regulations.\n\nOverall, Bayer Oberon Insecticide can be an effective tool for controlling insect pests and protecting crops and plants, but it should be used judiciously and with care to minimize potential risks to the environment and non-target organisms.",
    role: "seller",
    additionalInfo: [{}],
    totalSells: 0,
    totalQuantity: 0,
    category: "Insecticides",
    brand: "Bayer",
    date: "05/09/23 05:14 pm",
    __v: 0,
  },
  {
    _id: "645a2dbd699fe9b134776197",
    sellerName: "Istiak Ahmed",
    sellerEmail: "istiakahmed180@gmail.com",
    sellerPhone: "1734604086",
    sellerProfilePicture: "https://i.ibb.co/L99xrbX/Istiak-Ahmed.png",
    name: "Syngenta Kavach Fungicide",
    images: [
      "https://i.ibb.co/YdQXRYf/Image-1.webp",
      "https://i.ibb.co/Hnh0jPF/Image-2.webp",
      "https://i.ibb.co/sjqHKJg/Image-3.webp",
      "https://i.ibb.co/dQBjzV0/Image-4.webp",
    ],
    oldPrice: 830,
    newPrice: 699,
    size: [],
    stock: "INSTOCK",
    rating: 0,
    description:
      "Syngenta Kavach Fungicide is a systemic fungicide designed to protect crops from a wide range of fungal diseases. It is commonly used by farmers and gardeners to protect their crops from fungal infections that can cause serious damage and reduce yields.\n\nThe active ingredient in Syngenta Kavach Fungicide is Trifloxystrobin, which belongs to a class of chemicals called strobilurins. This chemical works by inhibiting the respiration process of the fungus, ultimately leading to its death.\n\nSyngenta Kavach Fungicide is typically applied as a spray or seed treatment. It is effective against a variety of fungal diseases, including rusts, leaf spots, powdery mildew, and blights.\n\nWhen using Syngenta Kavach Fungicide, it's important to follow the manufacturer's instructions carefully, as overuse or misuse can lead to unintended environmental consequences. It is also important to be aware of the potential risks to non-target organisms, such as bees and other beneficial insects, and to use the product responsibly and in accordance with local regulations.\n\nOverall, Syngenta Kavach Fungicide can be an effective tool for protecting crops from fungal diseases, but it should be used judiciously and with care to minimize potential risks to the environment and non-target organisms.",
    role: "seller",
    additionalInfo: [{}],
    totalSells: 1,
    totalQuantity: 0,
    category: "Fungicides",
    brand: "Syngenta",
    date: "05/09/23 05:24 pm",
    __v: 0,
  },
  {
    _id: "645a2edb699fe9b1347761c8",
    sellerName: "Istiak Ahmed",
    sellerEmail: "istiakahmed180@gmail.com",
    sellerPhone: "1734604086",
    sellerProfilePicture: "https://i.ibb.co/L99xrbX/Istiak-Ahmed.png",
    name: "Multiplex Jodi Fungicide",
    images: [
      "https://i.ibb.co/XJKmVYT/Image-1.webp",
      "https://i.ibb.co/3F8f4MG/Image-2.webp",
      "https://i.ibb.co/3c05tMN/Image-3.webp",
      "https://i.ibb.co/ctGKBKY/Image-4.webp",
    ],
    oldPrice: 360,
    newPrice: 106,
    size: [],
    stock: "INSTOCK",
    rating: 5,
    description:
      "Multiplex Jodi Fungicide is a systemic fungicide designed to control a wide range of fungal diseases in crops, gardens, and other plants. It is commonly used by farmers, gardeners, and landscapers to protect their crops and plants from harmful fungal infections.\n\nThe active ingredient in Multiplex Jodi Fungicide is Propiconazole, which belongs to a class of chemicals called triazoles. This chemical works by inhibiting the growth of the fungus, ultimately leading to its death.\n\nMultiplex Jodi Fungicide is typically applied as a spray or seed treatment. It is effective against a variety of fungal diseases, including rusts, leaf spots, powdery mildew, and blights.\n\nWhen using Multiplex Jodi Fungicide, it's important to follow the manufacturer's instructions carefully, as overuse or misuse can lead to unintended environmental consequences. It is also important to be aware of the potential risks to non-target organisms, such as bees and other beneficial insects, and to use the product responsibly and in accordance with local regulations.\n\nOverall, Multiplex Jodi Fungicide can be an effective tool for controlling fungal diseases and protecting crops and plants, but it should be used judiciously and with care to minimize potential risks to the environment and non-target organisms.",
    role: "seller",
    additionalInfo: [{}],
    totalSells: 0,
    totalQuantity: 0,
    category: "Fungicides",
    brand: "Multiplex",
    date: "05/09/23 05:29 pm",
    __v: 0,
  },
  {
    _id: "645a322d699fe9b13477620c",
    sellerName: "Istiak Ahmed",
    sellerEmail: "istiakahmed180@gmail.com",
    sellerPhone: "1734604086",
    sellerProfilePicture: "https://i.ibb.co/L99xrbX/Istiak-Ahmed.png",
    name: "BASF Lihocin - Growth Regulator",
    images: [
      "https://i.ibb.co/BNSmJk9/Image-1.webp",
      "https://i.ibb.co/42DMVvZ/Image-2.webp",
      "https://i.ibb.co/p47BgD1/Image-3.webp",
      "https://i.ibb.co/tMYLHsp/Image-4.webp",
    ],
    oldPrice: 475,
    newPrice: 224,
    size: [],
    stock: "INSTOCK",
    rating: 5,
    description:
      "BASF Lihocin is a growth regulator designed to improve the quality and yield of various crops by regulating their growth and development. It is commonly used by farmers and growers to improve the performance of their crops and increase their market value.\n\nThe active ingredient in BASF Lihocin is Chlormequat Chloride, which belongs to a class of chemicals called plant growth regulators. This chemical works by inhibiting the production of gibberellin, a plant hormone that promotes stem elongation and cell division, resulting in a more compact growth habit and increased resistance to lodging.\n\nBASF Lihocin is typically applied as a spray or soil drench. It is effective in improving the quality and yield of a wide range of crops, including cereals, vegetables, fruit trees, and ornamental plants.\n\nWhen using BASF Lihocin, it's important to follow the manufacturer's instructions carefully, as overuse or misuse can lead to unintended consequences, such as stunted growth or reduced yield. It is also important to be aware of the potential risks to non-target organisms and to use the product responsibly and in accordance with local regulations.\n\nOverall, BASF Lihocin can be an effective tool for improving the performance of crops and increasing their market value, but it should be used judiciously and with care to minimize potential risks to the environment and non-target organisms.",
    role: "seller",
    additionalInfo: [{}],
    totalSells: 0,
    totalQuantity: 0,
    category: "Growth Promoters",
    brand: "BASF",
    date: "05/09/23 05:43 pm",
    __v: 0,
  },
  {
    _id: "645a6b7f57f75d5716cfaaf6",
    sellerName: "Istiak Ahmed",
    sellerEmail: "istiakahmed180@gmail.com",
    sellerPhone: "1734604086",
    sellerProfilePicture: "https://i.ibb.co/L99xrbX/Istiak-Ahmed.png",
    name: "Samruddi Pro Rich Alpha Fruit Growth Promoter – FRGP",
    images: [
      "https://i.ibb.co/pXkNqFg/Image-1.webp",
      "https://i.ibb.co/9495B3V/Image-2.webp",
      "https://i.ibb.co/rZNC9tt/Image-3.webp",
      "https://i.ibb.co/wRj9jtM/Image-4.webp",
    ],
    oldPrice: 550,
    newPrice: 298,
    size: [],
    stock: "INSTOCK",
    rating: 5,
    description:
      "Samruddi Pro Rich Alpha Fruit Growth Promoter (FRGP) is a high-quality, plant-based product designed to enhance the growth and development of fruits. It is a combination of natural ingredients that provide essential nutrients and plant hormones to promote fruit growth, increase yield and improve fruit quality.\n\nThe active ingredients in Samruddi Pro Rich Alpha FRGP are derived from seaweed extracts, amino acids, and micronutrients. These ingredients are carefully selected to ensure that they are of the highest quality and purity.\n\nSeaweed extracts contain natural plant growth regulators such as cytokinins, gibberellins, and auxins, which promote cell division and elongation, leading to increased fruit size and weight. Amino acids provide the building blocks for proteins, which are essential for plant growth and development. Micronutrients such as zinc, iron, and manganese are important for enzyme activity and metabolic processes that influence fruit quality.\n\nSamruddi Pro Rich Alpha FRGP is easy to use and can be applied through drip irrigation or foliar spray. It is compatible with most fertilizers and pesticides, making it easy to integrate into existing crop management practices.\n\nThe use of Samruddi Pro Rich Alpha FRGP can lead to higher yields, larger and better quality fruits, and increased profits for farmers. It is an eco-friendly alternative to synthetic fertilizers and does not have any harmful effects on the environment or human health.",
    role: "seller",
    additionalInfo: [{}],
    totalSells: 0,
    totalQuantity: 0,
    category: "Growth Promoters",
    brand: "Samruddi",
    date: "05/09/23 09:47 pm",
    __v: 0,
  },
  {
    _id: "645a6dc457f75d5716cfab46",
    sellerName: "Istiak Ahmed",
    sellerEmail: "istiakahmed180@gmail.com",
    sellerPhone: "1734604086",
    sellerProfilePicture: "https://i.ibb.co/L99xrbX/Istiak-Ahmed.png",
    name: "Syngenta Zetrola Herbicide",
    images: [
      "https://i.ibb.co/GVC6nNX/Image-1.webp",
      "https://i.ibb.co/XZbKxTX/Image-2.webp",
      "https://i.ibb.co/30kd76f/Image-3.webp",
      "https://i.ibb.co/vBvRHDS/Image-4.webp",
    ],
    oldPrice: 635,
    newPrice: 227,
    size: [],
    stock: "INSTOCK",
    rating: 0,
    description:
      "\nSyngenta Zetrola Herbicide is a selective herbicide designed to control a wide range of grass and broadleaf weeds in various crops. The active ingredient in Zetrola Herbicide is pyroxasulfone, which works by inhibiting the growth of weeds by disrupting cell division and membrane function.\n\nZetrola Herbicide is a pre-emergent herbicide that is applied to the soil before the crop is planted or just after planting. It provides long-lasting control of weeds by preventing their emergence and growth. It is ideal for use in field crops, vegetables, fruit trees, and other crops.\n\nZetrola Herbicide has low volatility, which means that it does not easily evaporate into the atmosphere, reducing the risk of off-target movement and potential harm to non-target plants. It is also water-soluble, making it easy to apply and mix with other herbicides and fertilizers.\n\nZetrola Herbicide has a wide application window, allowing farmers to apply it before, during, or after planting. It can be applied using ground equipment or aerial spraying, depending on the crop and farming practices.\n\nWhen used as directed, Zetrola Herbicide is safe for crops and the environment. It is non-toxic to bees and other beneficial insects, and it does not accumulate in soil or groundwater. It has a low risk of phytotoxicity, meaning that it does not harm the crop plants.\n\nOverall, Syngenta Zetrola Herbicide is an effective and reliable herbicide option for farmers looking to control weeds and improve crop yields.",
    role: "seller",
    additionalInfo: [{}],
    totalSells: 0,
    totalQuantity: 0,
    category: "Herbicides",
    brand: "Syngenta",
    date: "05/09/23 09:57 pm",
    __v: 0,
  },
];
